@host=https://localhost:5001

###
GET {{host}}/api/claims

###
GET {{host}}/api/claims/42974

###
POST {{host}}/api/claims
Content-Type: application/json

{
    "contract": "Testvertrag",
    "claimAmount": 4200,
    "claimTimestamp": "2021-05-25T08:00:00"
}

###
DELETE {{host}}/api/claims/37218

###
PATCH {{host}}/api/claims/2704
Content-Type: application/json

{
    "contract": "FooBar"
}

###
POST https://demo.identityserver.io/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=m2m&client_secret=secret&audience=api

###
GET {{host}}/api/claims
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjUwRkQ3RkY1QjI0N0EwRDBENTYwMzYxMzJCMkQ0QUZFIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MjIwMzYxNTEsImV4cCI6MTYyMjAzOTc1MSwiaXNzIjoiaHR0cHM6Ly9kZW1vLmlkZW50aXR5c2VydmVyLmlvIiwiYXVkIjoiYXBpIiwiY2xpZW50X2lkIjoibTJtIiwianRpIjoiQkRDNDYzQTgxMTA3Njk0MjYwMThERTJFM0YxMERDMDkiLCJpYXQiOjE2MjIwMzYxNTEsInNjb3BlIjpbImFwaSIsImFwaS5zY29wZTEiLCJhcGkuc2NvcGUyIiwicG9saWN5c2VydmVyLm1hbmFnZW1lbnQiLCJwb2xpY3lzZXJ2ZXIucnVudGltZSIsInNjb3BlMiJdfQ.YCrhj6ETBCSc_sqRdVo6FFRT5-F4LSW7zMykuSfNmmR1cmmplyBod0qL4sDmhtILX5_Jt5KqMggMDj4B2AaAUxDqmGOuJH-MIXlmHqNivNlqeJSdYXMl8kOqlrRCIkmC4LN00yOlmiZdwINC3MCDQtvgPHIFZ8JE0Gq0LaNoufV_xKAKXX0VD_W333rzCRZvKpbmwti1fJpkpdgWyM7EUWyN7mZnxVmZcfZK6d9wYP4B6W40LyYqCfgUXRSOW7iSNnSWOe6D8YyzyIw3EhmP8NVgJ44EXUarR6U8TPU0cspfG6bnCyldW_lnvH9UYeV76AdyGV_VDZp1zjTuYq0Alg
